version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: pengajuan-dana-app
    container_name: pengajuan-dana-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - pengajuan-dana-network

  db:
    image: mysql:8.0
    container_name: pengajuan-dana-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - pengajuan-dana-network

  nginx:
    image: nginx:alpine
    container_name: pengajuan-dana-nginx
    restart: unless-stopped
    ports:
      - "9000:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - pengajuan-dana-network

networks:
  pengajuan-dana-network:
    driver: bridge

volumes:
  dbdata:
    driver: local